

services:
  mongo:
    image: mongo:6.0
    container_name: mean-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: raksha07/mean-backend:latest
    container_name: mean-backend
    restart: always
    environment:
      PORT: 3000
      MONGO_URI: mongodb://root:example@mongo:27017/?authSource=admin
    depends_on:
      - mongo

  frontend:
    image: raksha07/mean-frontend:latest
    container_name: mean-frontend
    restart: always
    depends_on:
      - backend

  reverse-proxy:
    image: nginx:latest
    container_name: mean-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:
