

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"   # optional: expose for local debugging
    environment:
      MONGO_INITDB_DATABASE: mean_crud
    volumes:
      - mongo_data:/data/db

  backend:
    image: ${DOCKERHUB_USERNAME}/mean-backend:${BACKEND_TAG:-latest}
    container_name: backend
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017/mean_crud
    ports:
      - "3000:3000"     # optional: expose for debugging
    # If you prefer building locally on the VM instead of pulling:
    # build: ./backend

  frontend:
    image: ${DOCKERHUB_USERNAME}/mean-frontend:${FRONTEND_TAG:-latest}
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    # build: ./frontend`
    # no env needed; it will call /api on same origin

  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  mongo_data:

